version: '3'
services:
  app:
    image: $DOCKER_REGISTRY/chad/gateway
    entrypoint: /bin/sh -c 'mkdir -p /run/secrets && echo test > /run/secrets/config_password && /entrypoint.sh'
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 8002:80
      - 8194:1194/tcp
