version: '3'
services:
  redis:
    image: redis:alpine
  app:
    image: $DOCKER_REGISTRY/chad/server
    build: .
    depends_on:
      - redis
    environment:
      - DEBUG=yes
      - CLEANUP_DISABLED=yes
      - CLEANUP_INTERVAL=5
      - CLEANUP_INSTANCE_TIMEOUT=20
      - CLEANUP_GATEWAY_TIMEOUT=10
      - DOCKER_REGISTRY=$DOCKER_REGISTRY
      - GATEWAY_IMAGE=$DOCKER_REGISTRY/chad/gateway
    ports:
      - 8001:80
    volumes:
      - ./pki:/etc/chad_pki
      - /var/run/docker.sock:/run/docker.sock
      - ./CHAD:/opt/CHAD:ro
